/*
 * GoBun replay download
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// DefaultApiController binds http requests to an api service and writes the service results to the http response
type DefaultApiController struct {
	service      DefaultApiServicer
	errorHandler ErrorHandler
}

// DefaultApiOption for how the controller is set up.
type DefaultApiOption func(*DefaultApiController)

// WithDefaultApiErrorHandler inject ErrorHandler into controller
func WithDefaultApiErrorHandler(h ErrorHandler) DefaultApiOption {
	return func(c *DefaultApiController) {
		c.errorHandler = h
	}
}

// NewDefaultApiController creates a default api controller
func NewDefaultApiController(s DefaultApiServicer, opts ...DefaultApiOption) Router {
	controller := &DefaultApiController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the DefaultApiController
func (c *DefaultApiController) Routes() Routes {
	return Routes{
		{
			"ReplayIdGet",
			strings.ToUpper("Get"),
			"/replay/{id}",
			c.ReplayIdGet,
		},
		{
			"StaffGet",
			strings.ToUpper("Get"),
			"/staff",
			c.StaffGet,
		},
	}
}

// ReplayIdGet - Get a replay
func (c *DefaultApiController) ReplayIdGet(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam := params["id"]

	result, err := c.service.ReplayIdGet(r.Context(), idParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeFileResponse(result.Body, result.Filename, &result.Code, w)

}

// StaffGet - Get a replay as staff
func (c *DefaultApiController) StaffGet(w http.ResponseWriter, r *http.Request) {
	query := r.URL.Query()
	idsParam := strings.Split(query.Get("ids"), ",")
	result, err := c.service.StaffGet(r.Context(), idsParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeFileResponse(result.Body, result.Filename, &result.Code, w)

}
