FROM golang:1.18

WORKDIR /usr/src/app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .


# Build script
RUN go build -v -o /usr/local/bin/editaddons ./scripts/addons/main.go &&\
    go build -v -o /usr/local/bin/sendcontainer ./scripts/containerinput/sendinput.go &&\
    go build -v -o /usr/local/bin/editservers ./scripts/kartserver/main.go
