version: "3.7"
services:

  discord:
    image: formulabun/discord:0.1.1
    build:
      context: ./discord
      dockerfile: Dockerfile
    environment:
      TOKEN: "${DISCORD_TOKEN}"
      APPLICATIONID: "${DISCORD_APPLICATION}"
      TESTGUILD: "${DISCORD_TESTGUILD}"

  translator:
    image: formulabun/translator:0.1.0
    build:
      context: ./translator
      dockerfile: Dockerfile
    ports:
      - "5092:5092/tcp"
    environment:
      TARGET: "${IP}:${SRB2KART_MAIN_PORT}"

  replays.store:
    image: formulabun/replaystore:0.0.0
    build:
      context: ./replays/store
      dockerfile: Dockerfile
    volumes:
      - replays:/data

  replays.download:
    image: formulabun/replaydownload:0.0.0
    build:
      context: ./replays/download
      dockerfile: Dockerfile
    volumes:
      - replays:/data
    
volumes:
  replays:
