FROM golang:1.18 AS build
WORKDIR /go/src

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

ENV CGO_ENABLED=0
RUN go get -d -v ./...

RUN go build -installsuffix cgo -gcflags=all="-N -l" -o openapi services/replays/store/server/main.go

FROM scratch AS runtime
VOLUME /data
COPY --from=build /go/src/openapi ./
EXPOSE 8080/tcp
ENTRYPOINT ["./openapi"]
