version: "3.7"
services:

  main:
    image: formulabun/srb2kart:1.6.0
    container_name: srb2kart
    restart: unless-stopped
    build:
      dockerfile: Dockerfile.srb2kart
    ports:
      - "${SRB2KART_MAIN_PORT}:${SRB2KART_MAIN_PORT}/udp"
    command: bonuschars.kart -port ${SRB2KART_MAIN_PORT}
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: "${LUAFILESOURCE}"
        target: "/luafiles"
      - type: bind
        source: "${CONFIGSOURCE}"
        target: "/configs"
      - type: volume
        source: addons
        target: "/addons"
      - type: bind
        source: "${ADDONSOURCE}"
        target: "/repo"

  addons:
    image: bash
    container_name: manage_addons
    volumes:
      - type: volume
        source: addons
        target: "/addonsmain"
      - type: bind
        source: "${ADDONSOURCE}"
        target: "/repo"

  discord:
    image: formulabun/discord:0.2.0
    container_name: discord
    restart: unless-stopped
    build:
      context: ./discord
      dockerfile: Dockerfile
    env_file: .env
    environment:
      TOKEN: "${DISCORD_TOKEN}"
      APPLICATIONID: "${DISCORD_APPLICATION}"
      TESTGUILD: "${DISCORD_TESTGUILD}"

  translator:
    image: formulabun/translator:1.0.0
    container_name: translator
    restart: unless-stopped
    build:
      context: ./translator
      dockerfile: Dockerfile
    ports:
      - "5092:5092/tcp"
    environment:
      TARGET: "${IP}:${SRB2KART_MAIN_PORT}"

  ingest.replays:
    image: formulabun/replaystore:0.1.0
    container_name: replaysingest
    ports:
      - "8080:8080/tcp"
    build:
      context: ./replays
      dockerfile: Dockerfile.ingest
    volumes:
      - replays:/data
    env_file: .env

  replays.staff:
    image: formulabun/replaystaff:0.1.0
    container_name: replaysstaff
    build:
      context: ./replays
      dockerfile: Dockerfile.staff
    volumes:
      - replays:/data

  replay.db:
    image: mariadb:10.5
    container_name: replaydb
    ports:
      - "3306:3306/tcp"
    environment:
      MARIADB_DATABASE: replays
    env_file: .env
    volumes:
      - ./databases/replays/test_init.sql:/docker-entrypoint-initdb.d/init.sql

  site:
    image: formulabun/site:1.0.0
    container_name: site
    ports:
      - "8080:8080/tcp"
    build:
      context: ./site
      dockerfile: Dockerfile
    
volumes:
  replays:
  addons:

