version: "3.7"
services:

  swagger:
    image: swaggerapi/swagger-ui
    network_mode:
      host
    ports:
      - 80:8080
    volumes:
      - /home/Fl_GUI/go/src/go.formulabun.club/replays/staff:/openapi
    environment:
      SWAGGER_JSON: /openapi/api.yml

  generate-server:
    image: openapitools/openapi-generator-cli
    volumes:
      - /home/Fl_GUI/go/src/go.formulabun.club/replays/ingest:/local
    command: generate -i /local/api.yml -g go-server -o /local/server

  generate-client:
    image: openapitools/openapi-generator-cli
    volumes:
      - /home/Fl_GUI/go/src/go.formulabun.club/replays/ingest:/local
    command: generate -i /local/api.yml -g go -o /local/client --additional-properties=\"isGoSubmodule=true\"
