version: "3.7"
services:

  main:
    image: formulabun/srb2kart:1.6.0
    build:
      dockerfile: Dockerfile.srb2kart
    ports:
      - "${SRB2KART_MAIN_PORT}:${SRB2KART_MAIN_PORT}/udp"
    command: bonuschars.kart -port ${SRB2KART_MAIN_PORT}
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: "${LUAFILESOURCE}"
        target: "/luafiles"
      - type: bind
        source: "${CONFIGSOURCE}"
        target: "/configs"
      - type: bind
        source: "${ADDONSOURCE}"
        target: "/addons"
