/*
 * Translator service between a srb2kart server and json
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type FileNeededInner struct {

	WillSend bool `json:"WillSend,omitempty"`

	TotalSize float32 `json:"TotalSize,omitempty"`

	FileName string `json:"FileName,omitempty"`

	MD5 []float32 `json:"MD5,omitempty"`
}

// AssertFileNeededInnerRequired checks if the required fields are not zero-ed
func AssertFileNeededInnerRequired(obj FileNeededInner) error {
	return nil
}

// AssertRecurseFileNeededInnerRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of FileNeededInner (e.g. [][]FileNeededInner), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseFileNeededInnerRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aFileNeededInner, ok := obj.(FileNeededInner)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertFileNeededInnerRequired(aFileNeededInner)
	})
}
