/*
 * Translator service between a srb2kart server and json
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PlayerInfoEntry struct {

	Node float32 `json:"Node,omitempty"`

	Name string `json:"Name,omitempty"`

	Address []float32 `json:"Address,omitempty"`

	Team float32 `json:"Team,omitempty"`

	Skin float32 `json:"Skin,omitempty"`

	Data float32 `json:"Data,omitempty"`

	Score float32 `json:"Score,omitempty"`

	TimeInServer float32 `json:"TimeInServer,omitempty"`
}

// AssertPlayerInfoEntryRequired checks if the required fields are not zero-ed
func AssertPlayerInfoEntryRequired(obj PlayerInfoEntry) error {
	return nil
}

// AssertRecursePlayerInfoEntryRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PlayerInfoEntry (e.g. [][]PlayerInfoEntry), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePlayerInfoEntryRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPlayerInfoEntry, ok := obj.(PlayerInfoEntry)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPlayerInfoEntryRequired(aPlayerInfoEntry)
	})
}
