/*
 * GoBun Replay File Info
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// DefaultApiService is a service that implements the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API.
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() DefaultApiServicer {
	return &DefaultApiService{}
}

// RootGet - Search replay info
func (s *DefaultApiService) RootGet(ctx context.Context) (ImplResponse, error) {
	// TODO - update RootGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []ReplayInfo{}) or use other options such as http.Ok ...
	//return Response(200, []ReplayInfo{}), nil

	//TODO: Uncomment the next line to return response Response(206, []ReplayInfo{}) or use other options such as http.Ok ...
	//return Response(206, []ReplayInfo{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("RootGet method not implemented")
}

// RootPost - Add a new replay info
func (s *DefaultApiService) RootPost(ctx context.Context, replayInfo ReplayInfo) (ImplResponse, error) {
	// TODO - update RootPost with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(201, {}) or use other options such as http.Ok ...
	//return Response(201, nil),nil

	//TODO: Uncomment the next line to return response Response(409, {}) or use other options such as http.Ok ...
	//return Response(409, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("RootPost method not implemented")
}
