/*
 * GoBun Replay File Info
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type MetaInfo struct {

	// discord id
	Creator int32 `json:"Creator,omitempty"`

	// unix time stamp
	Date int32 `json:"Date,omitempty"`
}

// AssertMetaInfoRequired checks if the required fields are not zero-ed
func AssertMetaInfoRequired(obj MetaInfo) error {
	return nil
}

// AssertRecurseMetaInfoRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of MetaInfo (e.g. [][]MetaInfo), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseMetaInfoRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aMetaInfo, ok := obj.(MetaInfo)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertMetaInfoRequired(aMetaInfo)
	})
}
