/*
 * GoBun Replay File Info
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type WadEntry struct {

	FileName string `json:"FileName,omitempty"`

	WadMd5 []int32 `json:"WadMd5,omitempty"`
}

// AssertWadEntryRequired checks if the required fields are not zero-ed
func AssertWadEntryRequired(obj WadEntry) error {
	return nil
}

// AssertRecurseWadEntryRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of WadEntry (e.g. [][]WadEntry), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseWadEntryRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aWadEntry, ok := obj.(WadEntry)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertWadEntryRequired(aWadEntry)
	})
}
