/*
 * GoBun Replay File Info
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ReplayInfo struct {

	MetaInfo MetaInfo `json:"MetaInfo,omitempty"`

	FileInfo FileInfo `json:"FileInfo,omitempty"`
}

// AssertReplayInfoRequired checks if the required fields are not zero-ed
func AssertReplayInfoRequired(obj ReplayInfo) error {
	if err := AssertMetaInfoRequired(obj.MetaInfo); err != nil {
		return err
	}
	if err := AssertFileInfoRequired(obj.FileInfo); err != nil {
		return err
	}
	return nil
}

// AssertRecurseReplayInfoRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ReplayInfo (e.g. [][]ReplayInfo), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseReplayInfoRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aReplayInfo, ok := obj.(ReplayInfo)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertReplayInfoRequired(aReplayInfo)
	})
}
