openapi: 3.0.0
info:
  title: GoBun File Store
  version: 0.0.1
servers:
- url: storage.replay
paths:
  /:
    post:
      requestBody:
        content:
          application/octet-stream:
            schema:
              format: binary
              type: string
        description: a replay file
        required: true
      responses:
        "201":
          description: created
        "400":
          description: bad replay file
        "409":
          description: conflicting checksum
      summary: Upload a new replay file
  /list:
    get:
      responses:
        "200":
          content:
            application/json:
              example:
              - MAP01-cream-time-best.lmp
              - MAP02-cream-time-best.lmp
              - MAP03-cream-time-best.lmp
              - MAP04-cream-time-best.lmp
              - MAP05-cream-time-best.lmp
              schema:
                items:
                  type: string
                type: array
          description: ok
      summary: Get the list of replay files
components:
  schemas: {}
